### ISSUE TITLE
[UAT test bug] Bot occasionally not displaying text - welcome event is hit but not text payloads not displayed. input hits the default fallback intent.

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#665] opened 2021-05-10 19:34 UTC
Can't reproduce it reliably, but it tends to happen after cache has been cleared.

see  https://open.rocket.chat/group/messaging?msg=YTMr8dK3MhSZtGmWK

https://my-viasat-preprod.icat.viasat.io

**Comment by Shailesh351** [comment] 2021-05-27 05:43
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:43 UTC
