### ISSUE TITLE
Livechat filters REST API should be idempotent if possible

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#703] opened 2021-05-21 15:47 UTC
At the moment it is possible to create the same filter twice.  This is an issue when using our version controller.  Is it possible to key on one of the values and have this Endpoint be idempotent?  FWIW - the Custom Fields endpoint works this way.

**Comment by Shailesh351** [comment] 2021-05-27 05:44
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:44 UTC
