### ISSUE TITLE
[2] escalated session: agent ending chat should trigger "Dialogflow Agent Ended Chat Event Name" event

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#568] opened 2021-03-23 14:55 UTC

**Comment by chadgoss** [comment] 2021-04-09 17:37
Pulled https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/28
and it's configured 

but, I'm not seeing end_live_chat in either user ends live chat or agent ends live chat

**Comment by Shailesh351** [comment] 2021-05-27 05:43
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:43 UTC
