### ISSUE TITLE
followupEventInput intent navigation is breaking "displayTyping": false settings

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#546] opened 2021-03-02 19:14 UTC

**Comment by chadgoss** [comment] 2021-03-09 20:05
The sequence is this:

1. Intent A is matched (intent A has displayTyping = True)
2. fulfillment response on intent A directs Dialogflow to followupEventInput to intent B (which has displayTyping = False)
3. Intent B response is displayed by RC, but typing indicator is showing

==============================
<img width="378" alt="Screen Shot 2021-03-09 at 2 55 07 PM" src="https://user-images.githubusercontent.com/9826215/110530845-e2c10280-80e8-11eb-8c1a-0e8bff386c65.png">

==============================

{
  "id": "aed9b19d-ae12-4321-b3ba-0a3d1bf7038d-9df18b51",
  "fulfillmentText": "Was I able to help you today?",
  "language_code": "en",
  "queryText": "go_to_g_anything_else",
  "webhookPayload": {},
  "intentDetectionConfidence": 1,
  "action": "",
  "webhookSource": "",
  "parameters": {
    "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
    "intent_name": "g_anything_else",
    "input_context_names": "to_g_anything_else",
    "ask_if_resolved_intent": "true"
  },
  "fulfillmentMessages": [
    {
      "text": {
        "text": [
          "Was I able to help you today?"
        ]
      }
    },
    {
      "payload": {
        "quick_replies": [
          {
            "title": "Yes",
            "content_type": "text",
            "payload": "Yes"
          },
          {
            "content_type": "text",
            "title": "No",
            "payload": "No"
          },
          {
            "payload": "Another question",
            "content_type": "text",
            "title": "Another question"
          },
          {
            "title": "Chat with agent",
            "payload": "Chat with agent",
            "content_type": "text"
          }
        ]
      }
    },
    {
      "payload": {
        "quickReplies": {
          "options": [
            {
              "text": "Yes",
              "buttonStyle": "primary"
            },
            {
              "text": "No",
              "buttonStyle": "primary"
            },
            {
              "text": "Another question",
              "buttonStyle": "primary"
            },
            {
              "buttonStyle": "primary",
              "text": "Chat with agent"
            }
          ]
        }
      }
    },
    {
      "payload": {
        "disableInput": true,
        "disableInputMessage": "Please select from the provided options"
      }
    },
    {
      "payload": {
        "customFields": {
          "disableInput": true,
          **"displayTyping": false,**
          "disableInputMessage": "Please select from the provided options"
        }
      }
    }
  ],
  "diagnosticInfo": {
    "webhook_latency_ms": 599
  },
  "webhookStatus": {
    "webhookStatus": {
      "message": "Webhook execution successful"
    },
    "webhookUsed": true
  },
  "outputContexts": [
    {
      "lifespanCount": 1,
      "name": "to_g_anything_else_yes",
      "parameters": {
        "intent_name.original": "",
        "input_context_names": "to_g_anything_else",
        "input_context_names.original": "",
        "output_context_names.original": "",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "ask_if_resolved_intent": "true",
        "ask_if_resolved_intent.original": "",
        "intent_name": "g_anything_else"
      }
    },
    {
      "lifespanCount": 1,
      "name": "to_g_anything_else_another_ques",
      "parameters": {
        "input_context_names": "to_g_anything_else",
        "output_context_names.original": "",
        "input_context_names.original": "",
        "intent_name": "g_anything_else",
        "ask_if_resolved_intent": "true",
        "intent_name.original": "",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "ask_if_resolved_intent.original": ""
      }
    },
    {
      "lifespanCount": 1,
      "name": "to_neuraflash_escalate",
      "parameters": {
        "input_context_names": "to_g_anything_else",
        "output_context_names.original": "",
        "ask_if_resolved_intent": "true",
        "intent_name": "g_anything_else",
        "ask_if_resolved_intent.original": "",
        "intent_name.original": "",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "input_context_names.original": ""
      }
    },
    {
      "lifespanCount": 1,
      "name": "to_g_anything_else_no",
      "parameters": {
        "input_context_names.original": "",
        "intent_name": "g_anything_else",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "output_context_names.original": "",
        "ask_if_resolved_intent.original": "",
        "intent_name.original": "",
        "ask_if_resolved_intent": "true",
        "input_context_names": "to_g_anything_else"
      }
    },
    {
      "lifespanCount": 996,
      "name": "previous_intent_info",
      "parameters": {
        "deflect_to_call_in": "true",
        "appName": "",
        "input_context_names.original": "",
        "discontinue_svc__Default.original": "",
        "output_context_names.original": "",
        "topic": "Account",
        "intent_name": "g_anything_else",
        "profile_name": "chad",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "roomId": "",
        "input_context_names": "to_g_anything_else",
        "intent_name.original": "",
        "topic.original": "",
        "intent_classification.original": "",
        "visitorToken": "",
        "ask_if_resolved_intent": "true",
        "deflect_to_call_in.original": "",
        "intent_classification": "account__cancellation_request__cancellation_request",
        "token": "",
        "discontinue_svc__Default": "https://help.viasat.com/s/article/Returning-leased-equipment-fees-and-instructions",
        "ask_if_resolved_intent.original": ""
      }
    },
    {
      "lifespanCount": 996,
      "name": "chat_source_myviasatweb",
      "parameters": {
        "ask_if_resolved_intent.original": "",
        "app": "MyViasatWeb",
        "ask_if_resolved_intent": "true",
        "deflect_to_call_in": "true",
        "device_type": "",
        "discontinue_svc__Default": "https://help.viasat.com/s/article/Returning-leased-equipment-fees-and-instructions",
        "output_context_names.original": "",
        "intent_classification": "account__cancellation_request__cancellation_request",
        "discontinue_svc__Default.original": "",
        "topic.original": "",
        "deflect_to_call_in.original": "",
        "page_url": "",
        "intent_name.original": "",
        "input_context_names.original": "",
        "output_context_names": "to_g_anything_else_yes, to_g_anything_else_another_ques, to_neuraflash_escalate, to_g_anything_else_no",
        "intent_classification.original": "",
        "intent_name": "g_anything_else",
        "topic": "Account",
        "input_context_names": "to_g_anything_else"
      }
    }
  ],
  "intent": {
    "isFallback": false,
    "displayName": "g_anything_else",
    "id": "5c8f9d6e-80ea-11eb-b434-acde48001122"
  }
}

**Comment by Shailesh351** [comment] 2021-05-27 05:43
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:43 UTC
