### ISSUE TITLE
[Upstream Demo] The chatroom list view is not set as the default start page

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#283] opened 2020-05-19 18:37 UTC
examples:  
- When first opening the PWA it starts on the Layout page, not on the chatroom list view.
- When closing out the my account page, it takes you to your last chat, and not to the list view.  

Previously we have had fixes for these things

**Comment by ear-dev** [comment] 2020-05-22 13:03
@Shailesh351 I did merge this PR, but I just tested it and the app still does not open with the chat list view.  The other issue, closing My Account page is now fixed.  Can you take a look and make another PR please?

**Comment by Shailesh351** [comment] 2020-05-22 14:59
@ear-dev I'm not able to reproduce first one
> When first opening the PWA it starts on the Layout page, not on the chatroom list view.

Can you give more details or something?

**Comment by Shailesh351** [comment] 2020-05-24 17:39
@ear-dev Very strange behaviour it is only happening after adding app in home screen. I will check start_url for pwa

**Comment by shubhsherl** [comment] 2020-05-25 10:02
Updated here: https://github.com/RocketChat/Rocket.Chat/pull/17549

**Comment by Shailesh351** [comment] 2020-07-14 14:03
Issue resolved. Hence Closing. Thanks @ear-dev @shubhsherl !!

**Closed as completed by Shailesh351** 2020-07-14 14:03 UTC
