### ISSUE TITLE
Another server crash

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#536] opened 2021-02-15 18:23 UTC
W20210215-18:21:32.517(0)? (STDERR) === UnHandledPromiseRejection ===
W20210215-18:21:32.518(0)? (STDERR) Error: No permission checker found for the bridge method "AppLivechatBridge.createMessage"
W20210215-18:21:32.518(0)? (STDERR) Please create a new cheker one under the permissionChekers folder to fix the issue.
W20210215-18:21:32.518(0)? (STDERR)     at Function.checkPermission (/home/ubuntu/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:47:19)
W20210215-18:21:32.518(0)? (STDERR)     at Proxy.<anonymous> (/home/ubuntu/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/managers/AppPermissionManager.js:18:68)
W20210215-18:21:32.519(0)? (STDERR)     at ModifyCreator._finishLivechatMessage (/home/ubuntu/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/accessors/ModifyCreator.js:100:49)
W20210215-18:21:32.519(0)? (STDERR)     at ModifyCreator.finish (/home/ubuntu/Rocket.Chat/node_modules/@rocket.chat/apps-engine/server/accessors/ModifyCreator.js:67:29)
W20210215-18:21:32.519(0)? (STDERR)     at evalmachine.<anonymous>:127:29
W20210215-18:21:32.519(0)? (STDERR)     at new Promise (<anonymous>)
W20210215-18:21:32.519(0)? (STDERR)     at Object.exports.createLivechatMessage (evalmachine.<anonymous>:126:12)
W20210215-18:21:32.519(0)? (STDERR)     at runMicrotasks (<anonymous>)
W20210215-18:21:32.520(0)? (STDERR)     at processTicksAndRejections (internal/process/task_queues.js:97:5)
W20210215-18:21:32.520(0)? (STDERR)     at ExecuteLivechatBlockActionHandler.run (evalmachine.<anonymous>:44:21)
W20210215-18:21:32.520(0)? (STDERR)     at DialogflowApp.executeLivechatBlockActionHandler (evalmachine.<anonymous>:21:16)
W20210215-18:21:32.520(0)? (STDERR) ---------------------------------
W20210215-18:21:32.520(0)? (STDERR) Errors like this can cause oplog processing errors.
W20210215-18:21:32.520(0)? (STDERR) Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
W20210215-18:21:32.521(0)? (STDERR) Future node.js versions will automatically exit the process
W20210215-18:21:32.521(0)? (STDERR) =================================

**Comment by Shailesh351** [comment] 2021-02-16 14:20
@chadgoss This was the issue from upstream regarding the new permission system they are developing for RC apps. It is already fixed and part of our latest upstream catchup PR. You can update node_modules for the same.

https://github.com/WideChat/Rocket.Chat/pull/535
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/379

**Comment by Shailesh351** [comment] 2021-02-16 14:29
https://docs.rocket.chat/apps-development/permission-system

**Comment by Shailesh351** [comment] 2021-05-27 05:42
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:42 UTC
