### ISSUE TITLE
[BLOCKING] RC server caching old appName and token

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#664] opened 2021-05-10 13:53 UTC
When a session is initiated, the appName and token are set in the room (every session has a unique room).

for some reason, the old appName and tokens are persisting to new rooms.

**Comment by Shailesh351** [comment] 2021-05-27 05:43
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:43 UTC
