### ISSUE TITLE
RC server crash

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#523] opened 2021-01-19 14:52 UTC
W20210119-14:48:50.418(0)? (STDERR) === UnHandledPromiseRejection ===
W20210119-14:48:50.419(0)? (STDERR) Error: Error occurred while processing handover. Details Error: [error-transferring-inquiry]
W20210119-14:48:50.420(0)? (STDERR)     at evalmachine.<anonymous>:80:15
W20210119-14:48:50.420(0)? (STDERR)     at /home/ubuntu/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20210119-14:48:50.420(0)? (STDERR) ---------------------------------
W20210119-14:48:50.420(0)? (STDERR) Errors like this can cause oplog processing errors.
W20210119-14:48:50.420(0)? (STDERR) Setting EXIT_UNHANDLEDPROMISEREJECTION will cause the process to exit allowing your service to automatically restart the process
W20210119-14:48:50.420(0)? (STDERR) Future node.js versions will automatically exit the process
W20210119-14:48:50.421(0)? (STDERR) =================================
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by Shailesh351** [comment] 2021-05-27 05:42
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:42 UTC
