### ISSUE TITLE
banner messages should be removed when bot is closed

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#553] opened 2021-03-10 18:14 UTC

**Comment by chadgoss** [comment] 2021-03-10 18:15
when the bot is closed any existing banner notifications should be cleared

<img width="376" alt="Screen Shot 2021-03-10 at 1 14 51 PM" src="https://user-images.githubusercontent.com/9826215/110677137-cf726d80-81a2-11eb-8621-367dc31fbb1d.png">

**Comment by Shailesh351** [comment] 2021-05-27 05:45
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:45 UTC
