### ISSUE TITLE
[UX Improvement] User notification when agent ends escalated chat.

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#585] opened 2021-04-02 13:38 UTC
Notify the user that the agent has ended the chat

Might fix itself after Bug 613

**Comment by chadgoss** [comment] 2021-04-08 15:20
verify that end_live_chat event is sent

**Comment by chadgoss** [comment] 2021-04-09 17:37
Pulled https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/28
and it's configured 

but, I'm not seeing end_live_chat in either user ends live chat or agent ends live chat

**Comment by Shailesh351** [comment] 2021-05-27 05:44
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:44 UTC
