### ISSUE TITLE
[3] Need to start session after user clicks on the icon, not when the page is loaded

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#693] opened 2021-05-19 14:24 UTC
High priority

**Comment by ear-dev** [comment] 2021-05-19 14:37
Is this an issue with RC or is this an implementation issue with how myViasat has embedded the widget and uses the js script?

**Comment by Shailesh351** [comment] 2021-05-19 15:16
@ear-dev It's the behavior of Rocket Chat Widget with `Start Session on new chat` setting enabled

**Comment by Shailesh351** [comment] 2021-05-27 05:44
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:44 UTC
