### ISSUE TITLE
[2] Conversation Finished Message consistency

### ISSUE THREAD

**Issue by chadgoss** [WideChat/Rocket.Chat#675] opened 2021-05-11 17:28 UTC
Omnichannel-->Livechat Appearance--> Conversation Finished Message

**Comment by chadgoss** [comment] 2021-05-11 17:31
It should show up as seen here "This is the Conversation Finished Message" in the following scenarios:
- agent ends escalated chat
- user 'X' out of conversation
<img width="367" alt="Screen Shot 2021-05-11 at 1 28 34 PM" src="https://user-images.githubusercontent.com/9826215/117859281-ca8e7080-b25c-11eb-91d1-0adbcc26ad74.png">

**Comment by chadgoss** [comment] 2021-05-11 17:32
It should not show up in the final window
<img width="371" alt="Screen Shot 2021-05-11 at 1 32 15 PM" src="https://user-images.githubusercontent.com/9826215/117859667-4e485d00-b25d-11eb-8058-c6754714085e.png">

**Comment by chadgoss** [comment] 2021-05-11 17:44
It should show up here instead of the "Chat finished" message when closing a chat during a conversation

<img width="260" alt="Screen Shot 2021-05-11 at 1 43 34 PM" src="https://user-images.githubusercontent.com/9826215/117860975-e5fa7b00-b25e-11eb-8c1e-cd012d37fd16.png">

**Comment by Shailesh351** [comment] 2021-05-27 05:44
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:44 UTC
