### ISSUE TITLE
[logging] Liveagent app should not ever log contents of a chat.

### ISSUE THREAD

**Issue by ear-dev** [WideChat/Rocket.Chat#620] opened 2021-04-20 15:30 UTC

**Comment by ear-dev** [comment] 2021-04-21 17:22
At the moment I think it is logging the salesforce agent side of the conversation, but not the client side.  Basically in all of our apps, we do not want to be logging any of the conversation history.

**Comment by Shailesh351** [comment] 2021-04-28 18:07
Fixed with https://github.com/WideChat/Rocket.Chat/issues/619

**Comment by Shailesh351** [comment] 2021-05-27 05:43
The issue is resolved. So closing this issue.

**Closed as completed by Shailesh351** 2021-05-27 05:43 UTC
